services:
  ruby:
    build:
      context: .
      dockerfile: ./docker_files/ruby
    environment:
      AWS_ENDPOINT: http://minio:9000
    volumes:
      - app_bundle:/usr/local/bundle
      - ./ruby:/app_root

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./docker_files/minio:/tmp/minio
    entrypoint: sh
    command: -c "
      minio server /data --address ':9000' --console-address ':9001';"
    # command: -c "
    #   mkdir -p /data/.minio.sys/;
    #   cp -r /tmp/minio/config /data/.minio.sys/.;
    #   cp -r /tmp/minio/data/* /data/.;
    #   mkdir /data/test.bucket;
    #   minio server /data --address ':9000' --console-address ':9001';"

  minio_mc:
    image: minio/mc:latest
    depends_on:
      - minio
    volumes:
      - ./docker_files/minio:/tmp/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    entrypoint: >
      /bin/sh -c "
      mc alias set play_with_minio http://minio:9000 minio minio123;
      mc mb --region ap-northeast-1 play_with_minio/sample.bucket;
      mc cp --recursive /tmp/minio/data/sample.bucket/* play_with_minio/sample.bucket;
      "


volumes:
  app_bundle:
    external: false
