aws:
  credential:
    access_key_id: sample_user
    secret_access_key: sample_user123
  s3:
    bucket: sample.bucket
    region: us-west-2
    endpoint: <%= ENV['AWS_ENDPOINT'] %>



## TODO: そのうち移動
main:
  upload_object_key: 'file/test.txt'
