name: ci

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_EC2_METADATA_DISABLED: true # これが必要な理由が理解できない
      AWS_ENDPOINT: http://localhost:9000

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          working-directory: ./ruby
          bundler-cache: true

      - name: Setup MinIO
        run: |
          mkdir -p /tmp/data/sample.bucket
          docker run -d --name minio \
                     -p 9000:9000 \
                     -e "MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}" \
                     -e "MINIO_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}" \
                     -v /tmp/data:/data \
                     minio/minio server /data

      - name: Run RSpec
        working-directory: ./ruby
        run: bundle exec rspec
